//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGP11.Tool.Domain.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configurations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configurations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iGP11.Tool.Domain.Configuration.Configurations", typeof(Configurations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: {
        ///    &quot;value&quot;: &quot;{2339DF7A-68B2-4313-B983-DA042C7FFD7A}&quot;
        ///  },
        ///  &quot;applicationCommunicationPort&quot;: 7320,
        ///  &quot;proxyCommunicationPort&quot;: 7321
        ///}
        ///.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: {
        ///    &quot;value&quot;: &quot;{6F3197DA-23A0-42E4-8B6E-2DD2AE86558D}&quot;
        ///  },
        ///  &quot;profileId&quot;: {
        ///    &quot;value&quot;: &quot;{ED4C83BD-5B83-45CA-9886-33A35CD05A42}&quot;
        ///  },
        ///  &quot;name&quot;: &quot;dark souls 2 scholar of the first sin&quot;,
        ///  &quot;filePath&quot;: &quot;&quot;,
        ///  &quot;profiles&quot;: [
        ///    {
        ///      &quot;id&quot;: {
        ///        &quot;value&quot;: &quot;{ED4C83BD-5B83-45CA-9886-33A35CD05A42}&quot;
        ///      },
        ///      &quot;gameId&quot;: {
        ///        &quot;value&quot;: &quot;{6F3197DA-23A0-42E4-8B6E-2DD2AE86558D}&quot;
        ///      },
        ///      &quot;name&quot;: &quot;development&quot;,
        ///      &quot;logsDirectoryPath&quot;: &quot;&lt;# app_dir #&gt;\\iGP11\\logs&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls2 {
            get {
                return ResourceManager.GetString("DarkSouls2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: {
        ///    &quot;value&quot;: &quot;{3B694522-C333-447A-B080-28F6DFDE9CD0}&quot;
        ///  },
        ///  &quot;profileId&quot;: {
        ///    &quot;value&quot;: &quot;{AAACDEC7-3AD2-46C5-82AF-E8E9DDFFB4AA}&quot;
        ///  },
        ///  &quot;name&quot;: &quot;dark souls 3&quot;,
        ///  &quot;filePath&quot;: &quot;&quot;,
        ///  &quot;profiles&quot;: [
        ///    {
        ///      &quot;id&quot;: {
        ///        &quot;value&quot;: &quot;{AAACDEC7-3AD2-46C5-82AF-E8E9DDFFB4AA}&quot;
        ///      },
        ///      &quot;gameId&quot;: {
        ///        &quot;value&quot;: &quot;{3B694522-C333-447A-B080-28F6DFDE9CD0}&quot;
        ///      },
        ///      &quot;name&quot;: &quot;development&quot;,
        ///      &quot;logsDirectoryPath&quot;: &quot;&lt;# app_dir #&gt;\\iGP11\\logs&quot;,
        ///      &quot;proxyDirectoryPath&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls3 {
            get {
                return ResourceManager.GetString("DarkSouls3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: {
        ///    &quot;value&quot;: &quot;{26E40BAF-4574-44CA-99C3-508F45928D6C}&quot;
        ///  },
        ///  &quot;profileId&quot;: {
        ///    &quot;value&quot;: &quot;{E3B7BFB4-1CB6-4026-B82B-B53BA56823ED}&quot;
        ///  },
        ///  &quot;name&quot;: &quot;fallout 4&quot;,
        ///  &quot;filePath&quot;: &quot;&quot;,
        ///  &quot;profiles&quot;: [
        ///    {
        ///      &quot;id&quot;: {
        ///        &quot;value&quot;: &quot;{E3B7BFB4-1CB6-4026-B82B-B53BA56823ED}&quot;
        ///      },
        ///      &quot;gameId&quot;: {
        ///        &quot;value&quot;: &quot;{26E40BAF-4574-44CA-99C3-508F45928D6C}&quot;
        ///      },
        ///      &quot;name&quot;: &quot;development&quot;,
        ///      &quot;proxyDirectoryPath&quot;: &quot;&lt;# app_dir #&gt;\\iGP11&quot;,
        ///      &quot;logsDirectoryPath&quot;: &quot;&lt;# app_d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fallout4 {
            get {
                return ResourceManager.GetString("Fallout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: {
        ///    &quot;value&quot;: &quot;{3F1F7B11-D204-4A15-8766-01C377175D11}&quot;
        ///  },
        ///  &quot;sourceDirectory&quot;: &quot;&quot;,
        ///  &quot;destinationDirectory&quot;: &quot;&quot;,
        ///  &quot;multiConversion&quot;: {
        ///    &quot;colorSpace&quot;: 0,
        ///    &quot;keepMipmaps&quot;: true,
        ///    &quot;outputFormat&quot;: 77
        ///  },
        ///  &quot;singleConversion&quot;: {
        ///    &quot;colorSpace&quot;: 0,
        ///    &quot;keepMipmaps&quot;: true,
        ///    &quot;outputFormat&quot;: 77
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string TextureManagementSettings {
            get {
                return ResourceManager.GetString("TextureManagementSettings", resourceCulture);
            }
        }
    }
}
