//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGP11.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iGP11.Tool.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme file is missing.
        /// </summary>
        public static string AboutFileMissing {
            get {
                return ResourceManager.GetString("AboutFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activation status not retrievable.
        /// </summary>
        public static string ActivationStatusNotRetrievable {
            get {
                return ResourceManager.GetString("ActivationStatusNotRetrievable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game not running.
        /// </summary>
        public static string ActivationStatusNotRunning {
            get {
                return ResourceManager.GetString("ActivationStatusNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin initialized.
        /// </summary>
        public static string ActivationStatusPluginActivated {
            get {
                return ResourceManager.GetString("ActivationStatusPluginActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin activation failed.
        /// </summary>
        public static string ActivationStatusPluginActivationFailed {
            get {
                return ResourceManager.GetString("ActivationStatusPluginActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin partially initialized, awaiting final initialization....
        /// </summary>
        public static string ActivationStatusPluginActivationPending {
            get {
                return ResourceManager.GetString("ActivationStatusPluginActivationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game running and plugin loaded.
        /// </summary>
        public static string ActivationStatusPluginLoaded {
            get {
                return ResourceManager.GetString("ActivationStatusPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game running.
        /// </summary>
        public static string ActivationStatusRunning {
            get {
                return ResourceManager.GetString("ActivationStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add profile.
        /// </summary>
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile.
        /// </summary>
        public static string AddProfileDialogTitle {
            get {
                return ResourceManager.GetString("AddProfileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to executable file path.
        /// </summary>
        public static string ApplicationFilePath {
            get {
                return ResourceManager.GetString("ApplicationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to executable file path: required.
        /// </summary>
        public static string ApplicationFilePathRequired {
            get {
                return ResourceManager.GetString("ApplicationFilePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game started.
        /// </summary>
        public static string ApplicationStarted {
            get {
                return ResourceManager.GetString("ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textures.
        /// </summary>
        public static string AvailableTextures {
            get {
                return ResourceManager.GetString("AvailableTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based on profile.
        /// </summary>
        public static string BasedOnProfile {
            get {
                return ResourceManager.GetString("BasedOnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth of field.
        /// </summary>
        public static string BokehDoF {
            get {
                return ResourceManager.GetString("BokehDoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagonal depth of field.
        /// </summary>
        public static string BokehDoFLongDescription {
            get {
                return ResourceManager.GetString("BokehDoFLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagonal depth of field.
        /// </summary>
        public static string BokehDoFShortDescription {
            get {
                return ResourceManager.GetString("BokehDoFShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot clear logging directory.
        /// </summary>
        public static string CannotClearLogsDirectory {
            get {
                return ResourceManager.GetString("CannotClearLogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot open logging directory.
        /// </summary>
        public static string CannotOpenLogsDirectory {
            get {
                return ResourceManager.GetString("CannotOpenLogsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check all.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication lost/could not be established.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication established.
        /// </summary>
        public static string CommunicationEstablished {
            get {
                return ResourceManager.GetString("CommunicationEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGP11 - COMMUNICATOR MODE.
        /// </summary>
        public static string CommunicatorMode {
            get {
                return ResourceManager.GetString("CommunicatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectToGame {
            get {
                return ResourceManager.GetString("ConnectToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration.
        /// </summary>
        public static string ConversionConfiguration {
            get {
                return ResourceManager.GetString("ConversionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert texture.
        /// </summary>
        public static string ConvertTexture {
            get {
                return ResourceManager.GetString("ConvertTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert textures.
        /// </summary>
        public static string ConvertTextures {
            get {
                return ResourceManager.GetString("ConvertTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoise.
        /// </summary>
        public static string Denoise {
            get {
                return ResourceManager.GetString("Denoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove noise from a signal.
        /// </summary>
        public static string DenoiseLongDescription {
            get {
                return ResourceManager.GetString("DenoiseLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove noise from a signal.
        /// </summary>
        public static string DenoiseShortDescription {
            get {
                return ResourceManager.GetString("DenoiseShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth buffer.
        /// </summary>
        public static string DepthBuffer {
            get {
                return ResourceManager.GetString("DepthBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust depth buffer settings to estimate right values for filters.
        /// </summary>
        public static string DepthBufferLongDescription {
            get {
                return ResourceManager.GetString("DepthBufferLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth buffer rendering.
        /// </summary>
        public static string DepthBufferShortDescription {
            get {
                return ResourceManager.GetString("DepthBufferShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct3d11.
        /// </summary>
        public static string Direct3D11 {
            get {
                return ResourceManager.GetString("Direct3D11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct3D11 plugin settings.
        /// </summary>
        public static string Direct3D11PluginSettings {
            get {
                return ResourceManager.GetString("Direct3D11PluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust plugin settings.
        /// </summary>
        public static string Direct3D11PluginSettingsLongDescription {
            get {
                return ResourceManager.GetString("Direct3D11PluginSettingsLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust plugin settings.
        /// </summary>
        public static string Direct3D11PluginSettingsShortDescription {
            get {
                return ResourceManager.GetString("Direct3D11PluginSettingsShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DisconnectFromGame {
            get {
                return ResourceManager.GetString("DisconnectFromGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify screen and render resolutions together with smoothness function to soften the edges.
        /// </summary>
        public static string DisplayLongDescription {
            get {
                return ResourceManager.GetString("DisplayLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render and screen resolution management.
        /// </summary>
        public static string DisplayShortDescription {
            get {
                return ResourceManager.GetString("DisplayShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string EditConfiguration {
            get {
                return ResourceManager.GetString("EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing any of those settings will cause an application to reload.
        /// </summary>
        public static string EditConfigurationDescription {
            get {
                return ResourceManager.GetString("EditConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} validation errors.
        /// </summary>
        public static string ErrorCount {
            get {
                return ResourceManager.GetString("ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string FatalErrorOccured {
            get {
                return ResourceManager.GetString("FatalErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game:.
        /// </summary>
        public static string GameHeader {
            get {
                return ResourceManager.GetString("GameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game name.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game profile.
        /// </summary>
        public static string GameProfile {
            get {
                return ResourceManager.GetString("GameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game profile name.
        /// </summary>
        public static string GameProfileName {
            get {
                return ResourceManager.GetString("GameProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure game settings and manage game profiles.
        /// </summary>
        public static string GameSettingsDescription {
            get {
                return ResourceManager.GetString("GameSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icons by.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process started and iGP11 launched.
        /// </summary>
        public static string InjectionCompleted {
            get {
                return ResourceManager.GetString("InjectionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launching application and loading plugin.
        /// </summary>
        public static string InjectionStarted {
            get {
                return ResourceManager.GetString("InjectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGP11 - STANDARD MODE.
        /// </summary>
        public static string InjectorMode {
            get {
                return ResourceManager.GetString("InjectorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insufficient permissions.
        /// </summary>
        public static string InsufficientPermissions {
            get {
                return ResourceManager.GetString("InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid configuration.
        /// </summary>
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip address data error.
        /// </summary>
        public static string IpAddressError {
            get {
                return ResourceManager.GetString("IpAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH GAME.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift gamma gain.
        /// </summary>
        public static string LiftGammaGain {
            get {
                return ResourceManager.GetString("LiftGammaGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control how gamma is applied to an image.
        /// </summary>
        public static string LiftGammaGainLongDescription {
            get {
                return ResourceManager.GetString("LiftGammaGainLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control how gamma is applied to an image.
        /// </summary>
        public static string LiftGammaGainShortDescription {
            get {
                return ResourceManager.GetString("LiftGammaGainShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging directory cleared.
        /// </summary>
        public static string LogsDirectoryCleared {
            get {
                return ResourceManager.GetString("LogsDirectoryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGP11 game logs directory path.
        /// </summary>
        public static string LogsDirectoryPath {
            get {
                return ResourceManager.GetString("LogsDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luma sharpening.
        /// </summary>
        public static string LumaSharpen {
            get {
                return ResourceManager.GetString("LumaSharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust image sharpening.
        /// </summary>
        public static string LumaSharpenLongDescription {
            get {
                return ResourceManager.GetString("LumaSharpenLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust image sharpening.
        /// </summary>
        public static string LumaSharpenShortDescription {
            get {
                return ResourceManager.GetString("LumaSharpenShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no endpoint listening at given address....
        /// </summary>
        public static string NoEndpointListening {
            get {
                return ResourceManager.GetString("NoEndpointListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No validation errors.
        /// </summary>
        public static string NoValidationErrors {
            get {
                return ResourceManager.GetString("NoValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open directory in explorer.
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opening the settings file failed.
        /// </summary>
        public static string OpeningSettingsFailed {
            get {
                return ResourceManager.GetString("OpeningSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation cancelled.
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation timeout.
        /// </summary>
        public static string OperationTimeout {
            get {
                return ResourceManager.GetString("OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin already loaded.
        /// </summary>
        public static string PluginAlreadyLoaded {
            get {
                return ResourceManager.GetString("PluginAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin:.
        /// </summary>
        public static string PluginHeader {
            get {
                return ResourceManager.GetString("PluginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin type.
        /// </summary>
        public static string PluginType {
            get {
                return ResourceManager.GetString("PluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin configuration updated at {0}.
        /// </summary>
        public static string ProcessConfigurationUpdated {
            get {
                return ResourceManager.GetString("ProcessConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating plugin configuration failed at {0}.
        /// </summary>
        public static string ProcessConfigurationUpdatingFailed {
            get {
                return ResourceManager.GetString("ProcessConfigurationUpdatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loaded profile: {0} {1}.
        /// </summary>
        public static string ProfileChanged {
            get {
                return ResourceManager.GetString("ProfileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile renamed.
        /// </summary>
        public static string ProfileRenamed {
            get {
                return ResourceManager.GetString("ProfileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfileType {
            get {
                return ResourceManager.GetString("ProfileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGP11 game directory path.
        /// </summary>
        public static string ProxyDirectoryPath {
            get {
                return ResourceManager.GetString("ProxyDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to install all prerequisites specified in readme.pdf and run this program with as high privileges as possible.
        ///
        ///In case of problems make sure Windows or any other installed program does not cripple iGP11 access to current and chosen game directories..
        /// </summary>
        public static string ReleaseNotesDescription {
            get {
                return ResourceManager.GetString("ReleaseNotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        public static string ReleaseNotesTitle {
            get {
                return ResourceManager.GetString("ReleaseNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove profile.
        /// </summary>
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile.
        /// </summary>
        public static string RemoveProfileDialogTitle {
            get {
                return ResourceManager.GetString("RemoveProfileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile?
        ///Profile data will be lost..
        /// </summary>
        public static string RemoveProfileQuestion {
            get {
                return ResourceManager.GetString("RemoveProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename profile.
        /// </summary>
        public static string RenameProfile {
            get {
                return ResourceManager.GetString("RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename profile.
        /// </summary>
        public static string RenameProfileDialogTitle {
            get {
                return ResourceManager.GetString("RenameProfileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha.
        /// </summary>
        public static string RenderingModeAlpha {
            get {
                return ResourceManager.GetString("RenderingModeAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depth buffer.
        /// </summary>
        public static string RenderingModeDepthBuffer {
            get {
                return ResourceManager.GetString("RenderingModeDepthBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to effects.
        /// </summary>
        public static string RenderingModeEffects {
            get {
                return ResourceManager.GetString("RenderingModeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to luminescence.
        /// </summary>
        public static string RenderingModeLuminescence {
            get {
                return ResourceManager.GetString("RenderingModeLuminescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string RenderingModeNone {
            get {
                return ResourceManager.GetString("RenderingModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings saving failed at {0}.
        /// </summary>
        public static string SavingSettingsFailed {
            get {
                return ResourceManager.GetString("SavingSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings saved at {0}.
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures converter.
        /// </summary>
        public static string TextureConverter {
            get {
                return ResourceManager.GetString("TextureConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture management.
        /// </summary>
        public static string TextureManagementDialogTitle {
            get {
                return ResourceManager.GetString("TextureManagementDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texture preview.
        /// </summary>
        public static string TexturePreview {
            get {
                return ResourceManager.GetString("TexturePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textures have been converted.
        /// </summary>
        public static string TexturesConversionCompleted {
            get {
                return ResourceManager.GetString("TexturesConversionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texture has been converted.
        /// </summary>
        public static string TexturesConversionCompleted1 {
            get {
                return ResourceManager.GetString("TexturesConversionCompleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} textures awaiting to be processed.
        /// </summary>
        public static string TexturesConversionInitialization {
            get {
                return ResourceManager.GetString("TexturesConversionInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textures conversion progress: {0}/{1}.
        /// </summary>
        public static string TexturesConversionProgress {
            get {
                return ResourceManager.GetString("TexturesConversionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure dumping or injecting behavior
        ///Copy textures to tex_override directory
        ///Retrieve dumped textures from tex_dump directory.
        /// </summary>
        public static string TexturesLongDescription {
            get {
                return ResourceManager.GetString("TexturesLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump/replace and adjust texture level of details.
        /// </summary>
        public static string TexturesShortDescription {
            get {
                return ResourceManager.GetString("TexturesShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone mapping.
        /// </summary>
        public static string Tonemap {
            get {
                return ResourceManager.GetString("Tonemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduce a greater dynamic range of luminosity.
        /// </summary>
        public static string TonemapLongDescription {
            get {
                return ResourceManager.GetString("TonemapLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduce a greater dynamic range of luminosity.
        /// </summary>
        public static string TonemapShortDescription {
            get {
                return ResourceManager.GetString("TonemapShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncheck all.
        /// </summary>
        public static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error occured.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE GAME.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} cannot be equal.
        /// </summary>
        public static string ValueEqual {
            get {
                return ResourceManager.GetString("ValueEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than {1}.
        /// </summary>
        public static string ValueLessThan {
            get {
                return ResourceManager.GetString("ValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is outside the range; acceptable &lt;{0}; {1}&gt;.
        /// </summary>
        public static string ValueOutsideRange {
            get {
                return ResourceManager.GetString("ValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is required.
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value too long.
        /// </summary>
        public static string ValueTooLong {
            get {
                return ResourceManager.GetString("ValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrance.
        /// </summary>
        public static string Vibrance {
            get {
                return ResourceManager.GetString("Vibrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the intensity of the more muted colors.
        /// </summary>
        public static string VibranceLongDescription {
            get {
                return ResourceManager.GetString("VibranceLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the intensity of the more muted colors.
        /// </summary>
        public static string VibranceShortDescription {
            get {
                return ResourceManager.GetString("VibranceShortDescription", resourceCulture);
            }
        }
    }
}
